# Generated by Django 2.2.9 on 2020-04-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0003_auto_20200418_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodels',
            name='class_or_reg',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='modelhist',
            name='r_2_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
